# -*- coding: utf-8 -*-
"""Confusion Matrix

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t2PO3qUerciOCm4JunRNTW-XMUZAo6JA
"""

# prompt: plot confusion matrix for laptops_cleaned.csv

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier # Example classifier

# Load the dataset
try:
  df = pd.read_csv('laptops_cleaned.csv')
except FileNotFoundError:
  print("Error: laptops_cleaned.csv not found. Please upload the file.")
  exit()

# Assuming 'Company' is the target variable, adjust if necessary
X = df.drop('Manufacturer', axis=1)
y = df['Manufacturer']

# Convert categorical features to numerical using one-hot encoding
X = pd.get_dummies(X)

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and train a classifier (replace with your chosen classifier)
clf = RandomForestClassifier(random_state=42)
clf.fit(X_train, y_train)

# Make predictions
y_pred = clf.predict(X_test)

# Compute the confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Plot the confusion matrix
plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=clf.classes_, yticklabels=clf.classes_)
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()