# -*- coding: utf-8 -*-
"""scale

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19-a3v6csdm8Mi20-Ir9wKSRuzCf-9DUw
"""

import pandas as pd
from sklearn import linear_model
from sklearn.preprocessing import StandardScaler

scale=StandardScaler()

df=pd.read_csv("newcar_data.csv")
df

X=df[['weight','volume']]
scaleedX=scale.fit_transform(X)
scaleedX

X=df[['co2_emmison']]
scaleedX=scale.fit_transform(X)
scaleedX